name: Jogo da Velha
on:
  issues:
    types: [opened]

jobs:
  play:
    if: startsWith(github.event.issue.title, 'tttp:')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout do C√≥digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar Jogada
        run: python scripts/engine.py
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Salvar Mudan√ßas no Perfil
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "ü§ñ IA realizou uma jogada" || echo "Sem mudan√ßas para salvar"
          git push
